apiVersion: v1
kind: Secret
metadata:
  name: blinddate-secrets
type: Opaque
stringData:
  # Base64 encoded values are NOT needed here if using stringData
  # Replace these placeholder values with your actual secrets
  DATABASE_URL: "postgres://default:xxx@exxx?sslmode=require"
  NEXTAUTH_SECRET: "admin" # Change this in production!
  BLOB_READ_WRITE_TOKEN: "xxx"
